// Tiny shared auth helpers for the pulpo.club paywall.
//
// Design choices, written down so future-me doesn't reinvent them:
//
//   * Users live in a single env var `USERS` formatted as
//       USERS="alice:$2a$10$abc...,bob:$2a$10$def..."
//     Why an env var instead of a DB? Because Phase-1 has <50 paid users
//     and Vercel env vars are diffable, free, and survive zero-downtime
//     deploys. Migrate to KV/Postgres when this gets painful.
//
//   * Passwords are bcrypt hashes (cost 10). Generated by
//     `automation/add_user.js`. We never see plaintext.
//
//   * Sessions are HMAC-signed cookies, stateless. Payload:
//       base64url(JSON({u: username, e: expiresAtUnix}))
//       + "." + base64url(HMAC-SHA256(payload, SESSION_SECRET))
//     Why not JWT? Because JWT brings a library + algorithm-confusion
//     footguns we don't need for a single-issuer single-audience cookie.
//
//   * Cookie is HttpOnly + Secure + SameSite=Lax + 14-day expiry.
//     14 days is long enough that paid users don't get logged out
//     mid-week, short enough that a stolen device window is bounded.

const crypto = require("crypto");
const bcrypt = require("bcryptjs");

const COOKIE_NAME = "pulpo_sess";
const SESSION_TTL_SECONDS = 60 * 60 * 24 * 14; // 14 days

function getUsers() {
  // Parse the USERS env var into a {username: bcryptHash} map.
  const raw = process.env.USERS || "";
  const out = {};
  for (const entry of raw.split(",")) {
    const trimmed = entry.trim();
    if (!trimmed) continue;
    // Hashes contain ":" only via separators in our format, but bcrypt hashes
    // themselves contain "$" not ":", so a single split on the first ":" is safe.
    const idx = trimmed.indexOf(":");
    if (idx < 1) continue;
    const user = trimmed.slice(0, idx).trim();
    const hash = trimmed.slice(idx + 1).trim();
    if (user && hash) out[user] = hash;
  }
  return out;
}

function getSecret() {
  const s = process.env.SESSION_SECRET;
  if (!s || s.length < 32) {
    // Fail loudly. A weak secret defeats the whole point.
    throw new Error("SESSION_SECRET env var must be set and ≥ 32 chars");
  }
  return s;
}

function b64url(buf) {
  return Buffer.from(buf).toString("base64")
    .replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function b64urlDecode(str) {
  str = str.replace(/-/g, "+").replace(/_/g, "/");
  while (str.length % 4) str += "=";
  return Buffer.from(str, "base64");
}

function sign(payload) {
  const data = b64url(JSON.stringify(payload));
  const mac = crypto.createHmac("sha256", getSecret()).update(data).digest();
  return data + "." + b64url(mac);
}

function verify(token) {
  if (!token || typeof token !== "string") return null;
  const dot = token.lastIndexOf(".");
  if (dot < 1) return null;
  const data = token.slice(0, dot);
  const sigGiven = token.slice(dot + 1);
  const sigExpected = b64url(
    crypto.createHmac("sha256", getSecret()).update(data).digest()
  );
  // constant-time compare
  const a = Buffer.from(sigGiven);
  const b = Buffer.from(sigExpected);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
  let payload;
  try {
    payload = JSON.parse(b64urlDecode(data).toString("utf8"));
  } catch {
    return null;
  }
  if (!payload || typeof payload !== "object") return null;
  if (typeof payload.e !== "number" || payload.e < Math.floor(Date.now() / 1000)) {
    return null; // expired
  }
  if (typeof payload.u !== "string" || !payload.u) return null;
  return payload;
}

function parseCookies(req) {
  const header = req.headers && (req.headers.cookie || req.headers.Cookie);
  if (!header) return {};
  const out = {};
  for (const piece of header.split(";")) {
    const eq = piece.indexOf("=");
    if (eq < 0) continue;
    const k = piece.slice(0, eq).trim();
    const v = piece.slice(eq + 1).trim();
    if (k) out[k] = decodeURIComponent(v);
  }
  return out;
}

function buildCookie(token, { clear = false } = {}) {
  const parts = [
    `${COOKIE_NAME}=${clear ? "" : token}`,
    "Path=/",
    "HttpOnly",
    "Secure",
    "SameSite=Lax",
  ];
  if (clear) {
    parts.push("Max-Age=0");
  } else {
    parts.push(`Max-Age=${SESSION_TTL_SECONDS}`);
  }
  return parts.join("; ");
}

async function checkPassword(username, password) {
  const users = getUsers();
  const hash = users[username];
  if (!hash) {
    // Run a dummy compare anyway to keep timing roughly constant.
    await bcrypt.compare(password || "x", "$2a$10$" + "a".repeat(53));
    return false;
  }
  return bcrypt.compare(password, hash);
}

function issueToken(username) {
  const exp = Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS;
  return sign({ u: username, e: exp });
}

function readSession(req) {
  const cookies = parseCookies(req);
  const tok = cookies[COOKIE_NAME];
  if (!tok) return null;
  return verify(tok);
}

module.exports = {
  COOKIE_NAME,
  checkPassword,
  issueToken,
  readSession,
  buildCookie,
};
